- updated for 0.8.2
Changed files:
    qemu-cc.patch -> 1.2
    qemu-dot.patch -> 1.2

diff --git a/qemu-cc.patch b/qemu-cc.patch
--- a/qemu-cc.patch
+++ b/qemu-cc.patch
@@ -1,12 +1,12 @@
---- qemu-0.8.1/configure~	2006-05-20 01:27:00.000000000 +0300
-+++ qemu-0.8.1/configure	2006-05-20 01:29:38.000000000 +0300
-@@ -294,8 +294,7 @@
- strip="${cross_prefix}${strip}"
- 
- if [ ! -x "`which $cc`" ] ; then
--    echo "Compiler $cc could not be found"
--    exit
-+    echo "Warning: Compiler $cc could not be found"
+--- qemu.orig/configure	2006-07-22 19:23:34.000000000 +0200
++++ qemu/configure	2006-08-04 15:16:48.263651500 +0200
+@@ -309,8 +309,7 @@
+ if $cc -c -o $TMPO $TMPC 2>/dev/null ; then
+   : C compiler works ok
+ else
+-    echo "ERROR: \"$cc\" either does not exist or does not work"
+-    exit 1
++    echo "Warning: \"$cc\" either does not exist or does not work"
  fi
  
  if test "$mingw32" = "yes" ; then
